"""Delivery — a two-phase, PR-last flow.

  push_branch : create/scaffold the destination repo (if new), then commit the generated
                code onto a working BRANCH — no PR yet. This is what Jenkins checks out and
                what Self-Heal pushes fixes onto.
  open_pr     : run at the very END, only after the Jenkins gate is green — opens the actual
                pull request from that branch, so reviewers only ever see a green, ready-to-
                merge PR.

Both fall back to a draft when GitHub isn't connected or no destination is configured.
"""
import os
import uuid
from pathlib import Path

from ..integration import github, scaffold
from ..llm import call_llm_json
from ..state import PipelineState

SYSTEM = """You write pull request descriptions. Given the story/target, the generated tests,
and the quality-gate results, draft a concise PR title and body: what the suite covers,
which flows/endpoints, and the gate outcomes.
Respond with ONLY a JSON object: {"title": "...", "body": "..."}"""

# generated file suffix -> folder it lands in inside the destination repo
_DEST = {".spec.ts": "tests", ".spec.js": "tests", ".k6.js": "perf",
         ".axe.json": "a11y", ".pact.json": "contract", ".semgrep.yml": "security"}


def _draft(state: PipelineState) -> dict:
    try:
        user = (f"Target: {state.get('story', {}).get('inputs', {})}\n"
                f"AC: {state.get('acceptance_criteria', '(none)')}\n"
                f"Gates: {[(g['gate'], g['verdict']) for g in state.get('gate_decisions', [])]}\n"
                f"Test files: {[Path(t['path']).name for t in state.get('test_artifacts', [])]}")
        raw = call_llm_json("pr_agent", SYSTEM, user)
        return {"title": raw["title"], "body": raw["body"]}
    except Exception:
        files = [Path(t["path"]).name for t in state.get("test_artifacts", [])]
        return {"title": "AI-generated test suite",
                "body": "Automated tests generated by the AI Testing Marketplace.\n\n"
                        + "\n".join(f"- {f}" for f in files)}


def _collect_files(state: PipelineState) -> tuple[dict, bool]:
    """The generated artifacts to publish, keyed by their destination path."""
    files: dict[str, str] = {}
    for art in state.get("test_artifacts", []):
        p = Path(art["path"])
        folder = next((v for suf, v in _DEST.items() if p.name.endswith(suf)), "tests")
        files[f"{folder}/{p.name}"] = p.read_text()
    for art in (state.get("security_artifacts", []) + state.get("a11y_artifacts", [])
                + state.get("contract_artifacts", [])):
        p = Path(art["path"])
        folder = next((v for suf, v in _DEST.items() if p.name.endswith(suf)), "scans")
        files[f"{folder}/{p.name}"] = p.read_text()
    has_automation = any(a.get("type") == "playwright" for a in state.get("test_artifacts", []))
    return files, has_automation


def push_branch(state: PipelineState) -> dict:
    """Phase 1: commit the generated code onto a working branch (no PR yet)."""
    inp = state.get("story", {}).get("inputs", {}) or {}
    dest = inp.get("dest_repo")
    new_repo = inp.get("new_repo")

    # Mock runs are fully simulated — never touch GitHub (no repo, branch, or PR side-effects).
    if os.environ.get("MOCK_LLM"):
        print("  [Delivery] mock run — skipping GitHub (no branch pushed)")
        return {"pr": {"status": "mock", "has_automation": True,
                       "url": "(mock run — no branch pushed, no PR opened)"}}

    # Regression targets an EXISTING suite repo (source_repo) rather than dest/new — recognise it here.
    tracks = set(state.get("run_config", {}).get("tracks", []))
    src_repo = inp.get("source_repo") or ""
    is_full_src = bool(src_repo) and src_repo.count("/") == 1 and not src_repo.startswith(("http", "repos/", "/", "."))
    reg_target = src_repo if ("regression" in tracks and is_full_src) else None

    if not github.connected() or not (dest or new_repo or reg_target):
        print("  [Delivery] no GitHub target — will draft a PR at the end")
        return {"pr": {"status": "draft", "url": "(draft only — connect GitHub + pick a destination repo to publish)"}}

    # Nothing generated to publish? Do NOT create a repo / scaffold / open an empty PR.
    gen, has_automation = _collect_files(state)
    if not gen:
        # Regression runs the repo's EXISTING cases — no generated files, but we still open a
        # working branch off the suite repo so Self-Heal can commit repairs and we can PR them.
        src = reg_target or (dest if (dest and "/" in dest) else "")
        if src:
            base = github.repo_info(src).get("default_branch", "main")
            branch = f"ai-reg/{uuid.uuid4().hex[:8]}"
            github.ensure_branch(src, branch, base)
            print(f"  [Delivery] regression working branch {src}@{branch} (Self-Heal commits repairs here)")
            return {"pr": {"repo": src, "branch": branch, "base": base, "status": "branch",
                           "has_automation": False, "files": 0}}
        print("  [Delivery] no generated tests — nothing to publish (skipping branch/PR)")
        return {"pr": {"status": "empty", "has_automation": False,
                       "url": "(no tests were generated — nothing to publish; check the UI agent output)"}}

    files, scaffolded = {}, False
    if new_repo:
        created = github.create_repo(new_repo, private=True,
                                     description="AI-generated test suite (AI Testing Marketplace)")
        dest = created["full_name"]

    # Ensure the destination has a runnable Playwright framework (package.json, config, pages,
    # fixtures) — scaffold it when missing so Jenkins' `npm install` / `npx playwright test` works.
    # If the repo already has a framework, we reuse it (the UI agent scans + builds on top).
    need_framework = True
    if not new_repo:
        try:
            fw = github.scan_framework(dest)
            need_framework = not (fw.get("ok") and fw.get("has_framework"))
        except Exception:
            need_framework = True
    if need_framework:
        files.update(scaffold.playwright_framework(
            base_url=inp.get("base_url", ""), app_name=inp.get("source_repo", dest)))
        scaffolded = True
        print(f"  [Delivery] {'created ' + dest + ' + ' if new_repo else ''}scaffolded Playwright framework "
              f"({'new repo' if new_repo else 'existing repo had none'})")

    files.update(gen)

    import time
    branch = f"ai-tests/{uuid.uuid4().hex[:8]}"
    r, last = None, None
    for attempt in range(3):   # GitHub API can transiently time out — retry (idempotent on the same branch)
        try:
            r = github.commit_files(dest, files, branch=branch, message="ci: publish generated tests")
            break
        except Exception as exc:
            last = exc
            print(f"  [Delivery] push attempt {attempt + 1} failed ({exc}); retrying…")
            time.sleep(2 * (attempt + 1))
    if r is None:
        raise last
    print(f"  [Delivery] pushed {r['committed']} file(s) to {dest}@{branch} (PR opens after CI is green)")
    return {"pr": {"repo": dest, "branch": branch, "base": r["base"], "files": r["committed"],
                   "scaffolded": scaffolded, "has_automation": has_automation, "status": "branch"}}


def open_pr(state: PipelineState) -> dict:
    """Phase 2 (final): open the PR from the branch — reached only once every gate, including
    the Jenkins gate, is green. So the PR is ready to merge the moment it appears."""
    pr = state.get("pr", {}) or {}
    draft = _draft(state)

    # Mock runs never open a real PR — show a drafted title/body only.
    if os.environ.get("MOCK_LLM"):
        print("  [PR Agent] mock run — PR drafted, not opened")
        return {"pr": {**pr, **draft, "url": "(mock run — PR not opened)", "mock": True}, "status": "done"}

    if not github.connected() or not pr.get("repo") or not pr.get("branch"):
        print(f"  [PR Agent] drafted PR (no GitHub target): {draft['title']}")
        return {"pr": {**pr, **draft, "url": pr.get("url", "(draft only)")}, "status": "done"}

    # No changes on the branch (e.g. regression passed first try, or nothing healed) → no PR to open.
    if github.compare_ahead(pr["repo"], pr.get("base", "main"), pr["branch"]) == 0:
        print("  [PR Agent] branch has no changes — no PR to open (nothing to merge)")
        return {"pr": {**pr, **draft, "url": "(no changes — no PR needed)"}, "status": "done"}

    jr = state.get("jenkins_report", {}) or {}
    ci_line = ""
    if jr.get("status") == "ran":
        ci_line = (f"\n\n> **CI:** Jenkins {jr.get('overall')} — "
                   f"{jr.get('passed', 0)} passed, {jr.get('failed', 0)} failed.")
    scaffold_line = ("\n\n> Includes a scaffolded Playwright framework (pages/, fixtures/, config, CI)."
                     if pr.get("scaffolded") else "")
    body = draft["body"] + scaffold_line + ci_line + "\n\n✅ Automation is green — ready to merge."

    result = github.open_pr(pr["repo"], pr["branch"], pr.get("base", "main"), draft["title"], body)
    print(f"  [PR Agent] opened PR #{result['number']} on {pr['repo']}: {result['url']} (ready to merge)")
    return {"pr": {**pr, **draft, "url": result["url"], "number": result["number"]}, "status": "done"}
