"""Scaffold a complete, runnable Playwright test framework for a NEW repository.

When the destination repo doesn't exist yet, the PR agent creates it and commits
this scaffold — framework + driver + config + base page object + auth fixture + CI —
so the generated specs drop into a real, working project (not loose files).
"""


def playwright_framework(base_url: str = "http://localhost:3000", app_name: str = "app") -> dict:
    base_url = base_url or "http://localhost:3000"
    files: dict[str, str] = {}

    files["package.json"] = """{
  "name": "e2e-suite",
  "private": true,
  "scripts": {
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "report": "playwright show-report"
  },
  "devDependencies": { "@playwright/test": "^1.47.0" }
}
"""

    files["playwright.config.ts"] = f"""import {{ defineConfig, devices }} from '@playwright/test';

export default defineConfig({{
  testDir: './tests',
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  reporter: [['list'], ['html', {{ open: 'never' }}]],
  use: {{
    baseURL: process.env.BASE_URL || '{base_url}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  }},
  projects: [{{ name: 'chromium', use: {{ ...devices['Desktop Chrome'] }} }}],
}});
"""

    # Base page object — the reusable driver layer agents extend/reuse.
    files["pages/BasePage.ts"] = """import { Page, expect, Locator } from '@playwright/test';

/** Base page object: shared navigation + interaction helpers all pages reuse. */
export class BasePage {
  constructor(protected readonly page: Page) {}

  async goto(path = '/') { await this.page.goto(path); }
  async expectPath(path: string | RegExp) { await expect(this.page).toHaveURL(path); }
  async clickButton(name: string | RegExp) { await this.page.getByRole('button', { name }).click(); }
  async fillByLabel(label: string | RegExp, value: string) { await this.page.getByLabel(label).fill(value); }
  async fillByPlaceholder(ph: string | RegExp, value: string) { await this.page.getByPlaceholder(ph).fill(value); }
  async expectVisible(locator: Locator) { await expect(locator).toBeVisible(); }
}
"""

    files["pages/LoginPage.ts"] = """import { Page } from '@playwright/test';
import { BasePage } from './BasePage';

/** Example page object — agents extend this pattern for new pages. */
export class LoginPage extends BasePage {
  constructor(page: Page) { super(page); }

  async login(email: string, password: string) {
    await this.goto(process.env.LOGIN_PATH || '/login');
    await this.fillByPlaceholder(/email|@/i, email).catch(async () => {
      await this.fillByLabel(/email/i, email);
    });
    await this.page.getByRole('textbox').nth(0).fill(email).catch(() => {});
    await this.clickButton(/log ?in|sign ?in/i);
  }
}
"""

    # Auth fixture — reusable "logged-in page" for tests that need a session.
    files["fixtures/auth.ts"] = """import { test as base } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';

/** Extends `test` with a `loggedInPage` fixture using env credentials. */
export const test = base.extend<{ loggedInPage: import('@playwright/test').Page }>({
  loggedInPage: async ({ page }, use) => {
    const login = new LoginPage(page);
    await login.login(process.env.LOGIN_EMAIL || '', process.env.LOGIN_PASSWORD || '');
    await use(page);
  },
});
export { expect } from '@playwright/test';
"""

    files["tests/.gitkeep"] = "# agent-generated specs are committed here\n"

    # Kept at ci/ (not .github/workflows/) so committing needs only `repo` scope, not `workflow`.
    # Move it to .github/workflows/ to enable CI (requires a token with the workflow scope).
    files["ci/e2e.yml"] = """name: E2E
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm install
      - run: npx playwright install --with-deps chromium
      - run: npm test
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
"""

    files[".gitignore"] = "node_modules/\nplaywright-report/\ntest-results/\n.env\n"

    files["README.md"] = f"""# E2E Test Suite

Auto-generated by the **AI Testing Marketplace** for `{app_name}`.

## Layout
- `pages/` — page objects (reusable driver layer). Extend `BasePage`.
- `fixtures/` — shared fixtures (e.g. `loggedInPage`).
- `tests/` — the generated specs.
- `playwright.config.ts` — base URL (`BASE_URL` env), reporters, chromium project.

## Run
```bash
npm install
npx playwright install chromium
BASE_URL={base_url} LOGIN_EMAIL=... LOGIN_PASSWORD=... npm test
```
"""
    return files
